'use strict';

const { test, describe } = require('node:test');
const assert = require('node:assert');
const path = require('path');
const fs = require('fs');
const os = require('os');
const { spawnSync } = require('child_process');
const { scan, formatReport, zoneEnd } = require('../scripts/cache-stability-check');

// 10 lines: volatile markers on lines 1-6 (the first-60% zone, zoneEnd(10) === 6),
// plain content on 7-8, a date outside the zone on line 9, plain content on 10.
const SAMPLE = [
  '# Notes',
  '2026-07-14 some line',
  'Updated at 14:32 today',
  'AUTO-GENERATED by tool',
  'id: 3fa85f64-5717-4562-b3fc-2c963f66afa6',
  '@import ./partials/notes-2026-07-14.md',
  'normal content',
  'more normal content',
  '2099-01-01 old date outside the zone',
  'end of file',
].join('\n');

const CLEAN = ['# Notes', '', 'Some regular text with no volatile content.', ''].join('\n');

describe('unit: zoneEnd', () => {
  test('is 60% of total lines, rounded up', () => {
    assert.strictEqual(zoneEnd(10), 6);
    assert.strictEqual(zoneEnd(5), 3);
    assert.strictEqual(zoneEnd(1), 1);
  });
});

describe('unit: scan categories', () => {
  test('detects an ISO date', () => {
    const findings = scan(SAMPLE);
    assert.ok(findings.some((f) => f.line === 2 && f.category === 'date'));
  });

  test('detects a time', () => {
    const findings = scan(SAMPLE);
    assert.ok(findings.some((f) => f.line === 3 && f.category === 'time'));
  });

  test('detects a generated/last-updated stamp', () => {
    const findings = scan(SAMPLE);
    assert.ok(findings.some((f) => f.line === 4 && f.category === 'stamp'));
  });

  test('detects a UUID-v4', () => {
    const findings = scan(SAMPLE);
    assert.ok(findings.some((f) => f.line === 5 && f.category === 'uuid'));
  });

  test('detects an @import line whose path has a date stamp', () => {
    const findings = scan(SAMPLE);
    assert.ok(findings.some((f) => f.line === 6 && f.category === 'import'));
  });

  test('an @import without a date/build stamp is not flagged', () => {
    const findings = scan('@import ./partials/plain.md');
    assert.strictEqual(findings.length, 0);
  });

  test('a volatile line past the first 60% is not flagged', () => {
    const findings = scan(SAMPLE);
    assert.ok(!findings.some((f) => f.line === 9));
  });

  test('plain content lines produce no findings', () => {
    const findings = scan(SAMPLE);
    assert.ok(!findings.some((f) => f.line === 7 || f.line === 10));
  });

  test('a clean file yields zero findings', () => {
    assert.deepStrictEqual(scan(CLEAN), []);
  });
});

describe('unit: formatReport', () => {
  test('zero findings is a single clean line', () => {
    const report = formatReport([]);
    assert.strictEqual(report.split('\n').length, 1);
    assert.match(report, /no volatile lines/);
  });

  test('findings render one line per finding plus an advisory summary', () => {
    const findings = scan(SAMPLE);
    const report = formatReport(findings);
    assert.match(report, /^L2 \[date\]:/m);
    assert.match(report, /move them to the end of the file or remove them/);
  });
});

describe('CLI', () => {
  const SCRIPT = path.join(__dirname, '..', 'scripts', 'cache-stability-check.js');

  test('exits 0 and prints findings for a volatile file', () => {
    const p = path.join(os.tmpdir(), `hush-cache-stability-${process.pid}.md`);
    fs.writeFileSync(p, SAMPLE);
    try {
      const r = spawnSync('node', [SCRIPT, p], { encoding: 'utf-8' });
      assert.strictEqual(r.status, 0);
      assert.match(r.stdout, /\[date\]/);
    } finally {
      fs.unlinkSync(p);
    }
  });

  test('exits 0 and prints the clean line for a clean file', () => {
    const p = path.join(os.tmpdir(), `hush-cache-stability-clean-${process.pid}.md`);
    fs.writeFileSync(p, CLEAN);
    try {
      const r = spawnSync('node', [SCRIPT, p], { encoding: 'utf-8' });
      assert.strictEqual(r.status, 0);
      assert.match(r.stdout, /no volatile lines/);
    } finally {
      fs.unlinkSync(p);
    }
  });

  test('exits 1 for an unreadable/missing file', () => {
    const missing = path.join(os.tmpdir(), `hush-cache-stability-missing-${process.pid}.md`);
    const r = spawnSync('node', [SCRIPT, missing], { encoding: 'utf-8' });
    assert.strictEqual(r.status, 1);
    assert.match(r.stderr, /cannot read/);
  });

  test('missing args prints usage and exits 1', () => {
    const r = spawnSync('node', [SCRIPT], { encoding: 'utf-8' });
    assert.strictEqual(r.status, 1);
    assert.match(r.stderr, /Usage/);
  });
});
